project:
  type: website

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: teams.qmd
        text: Find a Club
      - href: events.qmd
      - href: records.qmd
        text: Records

format:
  html:
    theme: bootstrap::morph
    css: bootstrap.css
    toc: true

editor: visual

