project:
  type: website

website:
  title: ""
  navbar:
    logo: images/swimmerlogo.png
    left:
      #- href: index.qmd
      #  text: Home
      - href: aboutus.qmd
        text: About Us
      - href: teams.qmd
        text: Find a Club
      - href: events.qmd
      - href: records.qmd
      
  sidebar:
    - title: "Records"
      style: "docked"
      background: light
      contents:
        - records.qmd
        - scyrecords.qmd
        - scmrecords.qmd
        - lcmrecords.qmd
       # - tutorial-2.qmd

format:
  html:
    theme: bootstrap::morph
    css: bootstrap.css
    toc: true

editor: visual

