## **New Mexico LMSC SCM Records**

Updated March 28, 2024.

```{r setup}
#| echo: false
#| message: false
pool_len = "SCM"
source("process_records.R")
library(kableExtra)
agegroups = c("18-24", "25-29", "30-34", "35-39", "40-44", "45-49", "50-54", "55-59", "60-64", "65-69", "70-74", "75-79", "80-84","85-89", "90-94")
```

### **Women's SCM Records**

```{r womens_records}
#| echo: false
##| paged-print: true
##| results: asis
#women's records
results_list <- list()
results_list <- list()
for(a in 1:length(agegroups)){
  tmp_table <- staterecords %>% 
    filter(Sex=="Women", Age.Group==agegroups[a]) %>%
        arrange(Stroke, Distance) %>% 
    select(Distance, Stroke, Time, Name, Season)
results_list[[a]] <- kbl(tmp_table, caption = paste0("Women ",agegroups[a]))
}

results_list[[1]]
results_list[[2]]
results_list[[3]]
results_list[[4]]
results_list[[5]]
results_list[[6]]
results_list[[7]]
results_list[[8]]
results_list[[9]]
results_list[[11]]
results_list[[12]]
results_list[[13]]
results_list[[14]]
results_list[[15]]
#results_list[[16]]
```

------------------------------------------------------------------------

### **Men's SCM Records**

```{r mens_records}
#| echo: false
##| paged-print: true
##| results: asis
#men's records
results_list <- list()
for(a in 1:length(agegroups)){
  tmp_table <- staterecords %>% 
    filter(Sex=="Men", Age.Group==agegroups[a]) %>%
        arrange(Stroke, Distance) %>% 
    select(Distance, Stroke, Time, Name, Season)
results_list[[a]] <- kbl(tmp_table, caption = paste0("Men ",agegroups[a]))
}

results_list[[1]]
results_list[[2]]
results_list[[3]]
results_list[[4]]
results_list[[5]]
results_list[[6]]
results_list[[7]]
results_list[[8]]
results_list[[9]]
results_list[[11]]
results_list[[12]]
results_list[[13]]
results_list[[14]]
results_list[[15]]
#results_list[[16]]
```
