---
title: "New Mexico LMSC Clubs"
---

+------------------------------------------------------------------------------------------------------------+-------------------+----------------------------+
| **Club**                                                                                                   | **Location**      | **Practice Times**         |
+------------------------------------------------------------------------------------------------------------+-------------------+----------------------------+
| [**Alien City Masters**](https://www.usms.org/clubs/alien-city-masters)                                    | Roswell, NM       |                            |
+------------------------------------------------------------------------------------------------------------+-------------------+----------------------------+
| [**Barracuda Swimming**](https://www.usms.org/clubs/barracuda-swimming)                                    | Albuquerque, NM   | M-F 4:45pm-5:45pm          |
|                                                                                                            |                   |                            |
|                                                                                                            |                   | Sat 10-11am                |
+------------------------------------------------------------------------------------------------------------+-------------------+----------------------------+
| [**BEAST Aquatics**](https://www.gomotionapp.com/team/nmslfzf/page/training-groups/masters)                | Albuquerque, NM   | M-F 12-1pm                 |
+------------------------------------------------------------------------------------------------------------+-------------------+----------------------------+
| [**Charger Aquatics**](https://www.gomotionapp.com/team/nmca/page/masters)                                 | Albuquerque, NM   | MWF 6:30-7:45am            |
|                                                                                                            |                   |                            |
|                                                                                                            |                   | Sat 6:30-8am               |
+------------------------------------------------------------------------------------------------------------+-------------------+----------------------------+
| [**Santa Fe Aquatic Club**](https://www.gomotionapp.com/team/nmsfac/page/masters-program)                  | Santa Fe, NM      |                            |
+------------------------------------------------------------------------------------------------------------+-------------------+----------------------------+
| [**Four Corners Aquatic Club (FCAT)**](https://www.gomotionapp.com/team/nmsfca/page/home)                  | Farmington, NM    | TWTh 6-7:30am              |
+------------------------------------------------------------------------------------------------------------+-------------------+----------------------------+
| [**High Altitude Masters (HAMsters)**](https://highaltitudemasters.org/)                                   | Santa Fe, NM      |                            |
+------------------------------------------------------------------------------------------------------------+-------------------+----------------------------+
| [**High Point Masters**](https://www.usms.org/clubs/highpoint-masters)                                     | Albuquerque, NM   | MWF 6:00-7:00am\           |
|                                                                                                            |                   | MF 12:00-1:00pm\           |
|                                                                                                            |                   | TTh 5:30-6:30pm\           |
|                                                                                                            |                   | Sat 8:00-9:00am            |
+------------------------------------------------------------------------------------------------------------+-------------------+----------------------------+
| [**Las Cruces Aquatic Team (LCAT)**](https://www.gomotionapp.com/team/nmslcat/page/home)                   | Las Cruces, NM    |                            |
+------------------------------------------------------------------------------------------------------------+-------------------+----------------------------+
| [Lobo Aquatic Club Masters](https://www.gomotionapp.com/team/nmlac/page/groups/masters)                    | Albuquerque, NM   | M-F 5:30-6:30am, Sat 7-8am |
+------------------------------------------------------------------------------------------------------------+-------------------+----------------------------+
| [**Los Alamos Aquatomics**](https://www.gomotionapp.com/team/nmlaa/page/home)                              | Los Alamos, NM    | MWF 6-7am                  |
+------------------------------------------------------------------------------------------------------------+-------------------+----------------------------+
| [**MAKO**](https://www.gomotionapp.com/team/nmstar/page/masters)                                           | Albuquerque, NM   |                            |
+------------------------------------------------------------------------------------------------------------+-------------------+----------------------------+
| [**Rio Grande Swim Club**](https://www.usms.org/clubs/rio-grande-swim-club-871)                            | Rio Rancho, NM    |                            |
+------------------------------------------------------------------------------------------------------------+-------------------+----------------------------+
| [**Roadrunners of Albuquerque Aquatics (RAAC)**](https://www.gomotionapp.com/team/nmvast/page/custom-page) | Albuquerque, NM   | M-F 5:30-6:30am            |
+------------------------------------------------------------------------------------------------------------+-------------------+----------------------------+
| [**Rogue Aquatics**](https://www.usms.org/clubs/rogue-masters)                                             | Santa Fe, NM      | MWF 12:30-1pm              |
+------------------------------------------------------------------------------------------------------------+-------------------+----------------------------+
| [**Southwest Masters Swimming**](https://www.usms.org/clubs/southwest-multi-sport-3113)                    | Albuquerque, NM   | MWF 5am                    |
+------------------------------------------------------------------------------------------------------------+-------------------+----------------------------+
| [**Taos Swim Club**](https://www.gomotionapp.com/team/nmtsc/page/adultsmasters-program)                    | Taos, NM          |                            |
+------------------------------------------------------------------------------------------------------------+-------------------+----------------------------+

: New Mexico Clubs {.striped .hover}

+-------------------------------------------------------------------------------------------+-------------------+--------------+
| [**Amarillo Masters Program**](https://www.usms.org/clubs/amarillo-masters-program-1217)  | Amarillo, TX      |              |
+-------------------------------------------------------------------------------------------+-------------------+--------------+
| [**Rio Grande Swim Club**](https://www.usms.org/clubs/rio-grande-swim-club-871)           | El Paso, TX       |              |
+-------------------------------------------------------------------------------------------+-------------------+--------------+
| [**Sun City Masters Swim Club**](https://suncityswimming.com/sun-city-masters-swim-club/) | El Paso, TX       |              |
+-------------------------------------------------------------------------------------------+-------------------+--------------+

West Texas Clubs {.striped .hover}
